# Neutralizes Arch-specific Omarchy commands on NixOS.
#
# A handful of `omarchy-*` scripts call pacman/yay or write to /etc, /usr,
# /boot — on NixOS they error or do damage. They live read-only at
# ~/.local/share/omarchy/bin/, so we can't delete them; instead we ship stub
# scripts in an override dir and make that dir win on PATH.
#
# PATH precedence (the tricky part): Omarchy unconditionally re-prepends
# $OMARCHY_PATH/bin in default/bash/envs (sourced by every interactive shell).
# So the override dir must be prepended AFTER that. We do the actual prepend at
# the tail of shell.nix's initExtra (right after sourcing Omarchy's rc), which
# guarantees sequential ordering. This module just creates the stub scripts
# (+ a sessionPath entry for non-interactive/systemd contexts).
{ config, lib, ... }:

let
  overrideDir    = ".local/share/omarchy-nixos-overrides";
  overrideDirAbs = "${config.home.homeDirectory}/${overrideDir}";

  # Arch-specific commands that must not run on NixOS (pacman/yay, mutable
  # /etc, /usr, /boot, and Omarchy-git workflows). The high-level install/remove
  # scripts are included too; otherwise they can continue after a fake
  # omarchy-pkg-add success and leave partial config behind.
  disabledCommands = [
    "omarchy-branch-set"
    "omarchy-channel-set"
    "omarchy-config-direct-boot"
    "omarchy-hibernation-remove"
    "omarchy-hibernation-setup"
    "omarchy-install-browser"
    "omarchy-install-chromium-google-account"
    "omarchy-install-dev-env"
    "omarchy-install-dropbox"
    "omarchy-install-gaming-geforce-now"
    "omarchy-install-gaming-gpu-lib32"
    "omarchy-install-gaming-heroic"
    "omarchy-install-gaming-lutris"
    "omarchy-install-gaming-moonlight"
    "omarchy-install-gaming-retroarch"
    "omarchy-install-gaming-steam"
    "omarchy-install-gaming-xbox-cloud"
    "omarchy-install-gaming-xbox-controllers"
    "omarchy-install-helix"
    "omarchy-install-nordvpn"
    "omarchy-install-once"
    "omarchy-install-tailscale"
    "omarchy-install-vscode"
    "omarchy-install-zed"
    "omarchy-migrate"
    "omarchy-pkg-add"
    "omarchy-pkg-aur-accessible"
    "omarchy-pkg-aur-add"
    "omarchy-pkg-aur-install"
    "omarchy-pkg-drop"
    "omarchy-pkg-install"
    "omarchy-pkg-missing"
    "omarchy-pkg-present"
    "omarchy-pkg-remove"
    "omarchy-plymouth-reset"
    "omarchy-plymouth-set"
    "omarchy-plymouth-set-by-theme"
    "omarchy-refresh-limine"
    "omarchy-refresh-pacman"
    "omarchy-refresh-plymouth"
    "omarchy-refresh-sddm"
    "omarchy-reinstall"
    "omarchy-reinstall-configs"
    "omarchy-reinstall-git"
    "omarchy-reinstall-pkgs"
    "omarchy-remove-browser"
    "omarchy-remove-dev-env"
    "omarchy-remove-gaming-geforce-now"
    "omarchy-remove-gaming-heroic"
    "omarchy-remove-gaming-lutris"
    "omarchy-remove-gaming-minecraft"
    "omarchy-remove-gaming-moonlight"
    "omarchy-remove-gaming-retroarch"
    "omarchy-remove-gaming-steam"
    "omarchy-remove-gaming-xbox-cloud"
    "omarchy-remove-gaming-xbox-controllers"
    "omarchy-remove-preinstalls"
    "omarchy-remove-security-fido2"
    "omarchy-remove-security-fingerprint"
    "omarchy-setup-dns"
    "omarchy-setup-security-fido2"
    "omarchy-setup-security-fingerprint"
    # Writes /etc/sudoers.d/99-omarchy-nopasswd-* — NixOS's generated sudoers
    # has no includedir, so the file would be silently ignored. Honest failure
    # instead; the declarative knob is security.sudo.wheelNeedsPassword.
    "omarchy-sudo-passwordless"
    "omarchy-toggle-hybrid-gpu"
    "omarchy-update"
    "omarchy-update-analyze-logs"
    "omarchy-update-aur-pkgs"
    "omarchy-update-branch"
    "omarchy-update-confirm"
    "omarchy-update-git"
    "omarchy-update-keyring"
    "omarchy-update-orphan-pkgs"
    "omarchy-update-perform"
    "omarchy-update-system-pkgs"
  ];

  # One shared body, keyed off $0's basename. It exits non-zero on purpose:
  # package/boot/system installers must not silently pretend they succeeded.
  unsupportedScript = ''
    #!/usr/bin/env bash
    # Auto-generated by modules/omarchy-nixos-compat.nix — do not edit.
    cmd="$(basename "$0")"
    printf '\033[0;33m▲ %s is managed declaratively on NixOS.\033[0m\n' "$cmd" >&2
    printf '  Edit /etc/nixos, then run: sudo nixos-rebuild switch --flake /etc/nixos#toonix\n' >&2
    exit 1
  '';

  stubFiles = lib.listToAttrs (map (cmd: {
    name = "${overrideDir}/${cmd}";
    value = { text = unsupportedScript; executable = true; };
  }) disabledCommands);

  specialFiles = {
    "${overrideDir}/omarchy-update-available" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Hide Waybar's Arch/Omarchy-git update indicator on NixOS.
        echo "Toonix updates are managed by NixOS rebuilds." >&2
        exit 1
      '';
    };

    "${overrideDir}/omarchy-update-available-reset" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        pkill -RTMIN+7 waybar 2>/dev/null || true
        exit 0
      '';
    };

    "${overrideDir}/omarchy-update-firmware" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        if ! command -v fwupdmgr >/dev/null 2>&1; then
          echo "fwupdmgr is unavailable; enable services.fwupd in /etc/nixos." >&2
          exit 1
        fi
        fwupdmgr refresh --force
        exec sudo fwupdmgr update
      '';
    };

    "${overrideDir}/omarchy-install-terminal" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        if [ "$#" -eq 0 ]; then
          echo "Usage: omarchy-install-terminal [alacritty|foot|ghostty|kitty]" >&2
          exit 1
        fi

        case "$1" in
          alacritty|foot|ghostty|kitty) ;;
          *)
            echo "Unknown terminal: $1" >&2
            exit 1
            ;;
        esac

        if ! command -v "$1" >/dev/null 2>&1; then
          echo "$1 is not installed; add it to environment.systemPackages in /etc/nixos." >&2
          exit 1
        fi

        exec omarchy-default-terminal "$1"
      '';
    };

    "${overrideDir}/omarchy-debug" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        no_sudo=false
        print_only=false

        while [ "$#" -gt 0 ]; do
          case "$1" in
            --no-sudo)
              no_sudo=true
              shift
              ;;
            --print)
              print_only=true
              shift
              ;;
            *)
              echo "Unknown option: $1" >&2
              echo "Usage: omarchy-debug [--no-sudo] [--print]" >&2
              exit 1
              ;;
          esac
        done

        log_file="/tmp/omarchy-debug.log"

        if [ "$no_sudo" = true ]; then
          dmesg_output="(skipped - --no-sudo flag used)"
        else
          dmesg_output="$(sudo dmesg 2>&1 || true)"
        fi

        current_system="$(readlink -f /run/current-system 2>/dev/null || true)"
        current_sw="$(readlink -f /run/current-system/sw 2>/dev/null || true)"

        {
          echo "Date: $(date)"
          echo "Hostname: $(hostname)"
          echo "Toonix config: $(readlink -f /etc/nixos 2>/dev/null || echo /etc/nixos)"
          echo "Omarchy version: $(cat "$OMARCHY_PATH/version" 2>/dev/null || echo unknown)"
          echo "Current system: ''${current_system:-unknown}"
          echo
          echo "========================================="
          echo "SYSTEM INFORMATION"
          echo "========================================="
          if command -v inxi >/dev/null 2>&1; then
            inxi -Farz || true
          else
            uname -a
            command -v nixos-version >/dev/null 2>&1 && nixos-version || true
          fi
          echo
          echo "========================================="
          echo "DMESG"
          echo "========================================="
          echo "$dmesg_output"
          echo
          echo "========================================="
          echo "JOURNALCTL (CURRENT BOOT, WARNINGS+ERRORS)"
          echo "========================================="
          journalctl -b -p 4..1 2>&1 || true
          echo
          echo "========================================="
          echo "NIXOS GENERATIONS"
          echo "========================================="
          if command -v nix-env >/dev/null 2>&1; then
            sudo nix-env --list-generations --profile /nix/var/nix/profiles/system 2>&1 || true
          else
            echo "nix-env unavailable"
          fi
          echo
          echo "========================================="
          echo "CURRENT SYSTEM PACKAGES"
          echo "========================================="
          if command -v nix-store >/dev/null 2>&1 && [ -n "$current_sw" ]; then
            nix-store -q --references "$current_sw" 2>/dev/null | sed 's#.*/##' | sort || true
          else
            echo "nix-store unavailable"
          fi
        } > "$log_file"

        if [ "$print_only" = true ]; then
          cat "$log_file"
          exit 0
        fi

        options=("View log" "Save in current directory")
        if ping -c 1 8.8.8.8 >/dev/null 2>&1; then
          options=("Upload log" "''${options[@]}")
        fi

        action="$(gum choose "''${options[@]}")"

        case "$action" in
          "Upload log")
            echo "Uploading debug log to logs.omarchy.org..."
            url="$(curl -sf -F "file=@$log_file" https://logs.omarchy.org/ || true)"
            if [ -n "$url" ]; then
              echo "Log uploaded successfully:"
              echo "$url"
            else
              echo "Error: failed to upload log file" >&2
              exit 1
            fi
            ;;
          "View log")
            less "$log_file"
            ;;
          "Save in current directory")
            cp "$log_file" "./omarchy-debug.log"
            echo "Log saved to $(pwd)/omarchy-debug.log"
            ;;
        esac
      '';
    };

    "${overrideDir}/omarchy-hw-vulkan" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        # NixOS exposes driver data through profile/OpenGL paths, not /usr/share.
        for dir in \
          /run/opengl-driver/share/vulkan/icd.d \
          /run/opengl-driver-32/share/vulkan/icd.d \
          /run/current-system/sw/share/vulkan/icd.d \
          "$HOME/.nix-profile/share/vulkan/icd.d" \
          "/etc/profiles/per-user/$USER/share/vulkan/icd.d"; do
          if [ -d "$dir" ] && find "$dir" -maxdepth 1 -name '*.json' -print -quit | grep -q .; then
            exit 0
          fi
        done

        if command -v vulkaninfo >/dev/null 2>&1 && vulkaninfo --summary >/dev/null 2>&1; then
          exit 0
        fi

        exit 1
      '';
    };

    "${overrideDir}/omarchy-version-branch" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        echo "toonix/main"
      '';
    };

    "${overrideDir}/omarchy-version-channel" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        echo "nixos-unstable"
      '';
    };

    "${overrideDir}/omarchy-version-pkgs" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        if [ -e /run/current-system ]; then
          date -d "@$(stat -Lc %Y /run/current-system)" "+%A, %B %d %Y at %H:%M"
        else
          echo "unknown"
        fi
      '';
    };

    "${overrideDir}/omarchy-upload-log" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        log_type="''${1:-install}"
        temp_log="/tmp/upload-log.txt"
        system_info="/tmp/system-info.txt"

        {
          echo "========================================="
          echo "SYSTEM INFORMATION"
          echo "========================================="
          if command -v fastfetch >/dev/null 2>&1; then
            fastfetch --logo none --pipe 2>/dev/null || true
          else
            echo "Hostname: $(uname -n)"
            echo "Kernel: $(uname -r)"
            command -v nixos-version >/dev/null 2>&1 && echo "NixOS: $(nixos-version)" || true
            echo "Date: $(date)"
          fi
          echo
          echo "========================================="
          echo "LOG CONTENT"
          echo "========================================="
          echo
        } > "$system_info"

        case "$log_type" in
          install)
            if [ -s /mnt/var/log/nixos-install.log ]; then
              install_log="/mnt/var/log/nixos-install.log"
            elif [ -s /var/log/nixos-install.log ]; then
              install_log="/var/log/nixos-install.log"
            elif [ -s /mnt/var/log/omarchy-install.log ]; then
              install_log="/mnt/var/log/omarchy-install.log"
            elif [ -s /var/log/omarchy-install.log ]; then
              install_log="/var/log/omarchy-install.log"
            else
              install_log=""
            fi

            cat "$system_info" > "$temp_log"
            if [ -n "$install_log" ]; then
              printf '\n=========================================\nINSTALL LOG (%s)\n=========================================\n\n' "$install_log" >> "$temp_log"
              cat "$install_log" >> "$temp_log"
            else
              echo "Warning: install log not found." >&2
            fi
            echo "Uploading installation log to logs.omarchy.org..."
            ;;

          this-boot)
            cat "$system_info" > "$temp_log"
            journalctl -b 0 >> "$temp_log" 2>/dev/null || true
            echo "Uploading current boot logs to logs.omarchy.org..."
            ;;

          last-boot)
            cat "$system_info" > "$temp_log"
            journalctl -b -1 >> "$temp_log" 2>/dev/null || true
            echo "Uploading previous boot logs to logs.omarchy.org..."
            ;;

          installed|system-info)
            cat "$system_info" > "$temp_log"
            {
              echo
              echo "========================================="
              echo "NIXOS SYSTEM PATH"
              echo "========================================="
              readlink -f /run/current-system 2>/dev/null || true
              echo
              echo "========================================="
              echo "CURRENT SYSTEM PACKAGES"
              echo "========================================="
              if command -v nix-store >/dev/null 2>&1; then
                nix-store -q --references /run/current-system/sw 2>/dev/null | sed 's#.*/##' | sort || true
              else
                echo "nix-store unavailable"
              fi
            } >> "$temp_log"
            echo "Uploading system information to logs.omarchy.org..."
            ;;

          *)
            echo "Usage: $0 [install|this-boot|last-boot|installed|system-info]" >&2
            exit 1
            ;;
        esac

        echo
        url="$(curl -sf -F "file=@$temp_log" https://logs.omarchy.org/ || true)"
        if [ -n "$url" ]; then
          echo "Log uploaded successfully:"
          echo "$url"
        else
          echo "Error: failed to upload log file" >&2
          exit 1
        fi
      '';
    };

    "${overrideDir}/omarchy-voxtype-install" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        if ! command -v voxtype >/dev/null 2>&1; then
          echo "voxtype is not installed; add pkgs.voxtype to /etc/nixos." >&2
          exit 1
        fi

        if gum confirm "Download Voxtype AI model (~150MB) and enable dictation?"; then
          mkdir -p "$HOME/.config/voxtype"
          cp "$OMARCHY_PATH/default/voxtype/config.toml" "$HOME/.config/voxtype/config.toml"

          voxtype setup --download --no-post-install
          if omarchy-hw-vulkan; then
            voxtype setup gpu --enable || true
          fi
          voxtype setup systemd
          systemctl --user enable --now voxtype.service 2>/dev/null || true

          omarchy-restart-waybar
          notify-send "    Voxtype Dictation Ready" "Hold F9 to dictate (or toggle with Super + Ctrl + X)." -t 10000
        fi
      '';
    };

    "${overrideDir}/omarchy-voxtype-remove" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        systemctl --user disable --now voxtype.service 2>/dev/null || true
        rm -f "$HOME/.config/systemd/user/voxtype"*
        systemctl --user daemon-reload 2>/dev/null || true
        rm -rf "$HOME/.config/voxtype" "$HOME/.local/share/voxtype"
        omarchy-restart-waybar
        echo "Voxtype user configuration and model data removed. The package remains declared in /etc/nixos."
      '';
    };

    "${overrideDir}/omarchy-voxtype-status" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        # Reap the `voxtype status --follow` child when waybar reloads/kills this
        # module; without it each reload orphans a follower process (leak).
        trap 'kill 0' EXIT

        if ! command -v voxtype >/dev/null 2>&1; then
          echo '{"alt": "", "tooltip": ""}'
          exit 0
        fi

        if ! systemctl --user is-active --quiet voxtype.service 2>/dev/null; then
          echo '{"alt": "", "tooltip": "Voxtype not configured"}'
          exit 0
        fi

        voxtype status --follow --extended --format json | while read -r line; do
          echo "$line" | jq -c '. + {alt: .class}'
        done
      '';
    };
  };
in
{
  home.file = stubFiles // specialFiles;

  # Covers non-interactive contexts (systemd user units, SSH non-login). The
  # interactive/GUI-terminal win is handled in shell.nix (ordering-guaranteed).
  home.sessionPath = [ overrideDirAbs ];
}
