# Neutralizes Arch-specific Omarchy commands on NixOS.
#
# A handful of `omarchy-*` scripts call pacman/yay or write to /etc, /usr,
# /boot — on NixOS they error or do damage. They live read-only at
# ~/.local/share/omarchy/bin/, so we can't delete them; instead we ship stub
# scripts in an override dir and make that dir win on PATH.
#
# PATH precedence (the tricky part): Omarchy unconditionally re-prepends
# $OMARCHY_PATH/bin in default/bash/envs (sourced by every interactive shell).
# So the override dir must be prepended AFTER that. We do the actual prepend at
# the tail of shell.nix's initExtra (right after sourcing Omarchy's rc), which
# guarantees sequential ordering. This module just creates the stub scripts
# (+ a sessionPath entry for non-interactive/systemd contexts).
{ config, lib, ... }:

let
  overrideDir    = ".local/share/omarchy-nixos-overrides";
  overrideDirAbs = "${config.home.homeDirectory}/${overrideDir}";

  # Arch-specific commands that must not run on NixOS (pacman/sudo/boot writes).
  disabledCommands = [
    "omarchy-update"
    "omarchy-pkg-add"
    "omarchy-pkg-remove"
    "omarchy-pkg-install"
    "omarchy-pkg-aur-install"
    "omarchy-refresh-pacman"
    "omarchy-refresh-sddm"
    "omarchy-refresh-plymouth"
    "omarchy-refresh-limine"
    "omarchy-toggle-hybrid-gpu"
    "omarchy-migrate"
  ];

  # One shared body, keyed off $0's basename, exits 0 so the `omarchy`
  # dispatcher treats it as a clean no-op rather than a failure.
  stubScript = ''
    #!/usr/bin/env bash
    # Auto-generated by modules/omarchy-nixos-compat.nix — do not edit.
    cmd="$(basename "$0")"
    printf '\033[0;33m▲ %s is disabled on NixOS — manage this via your flake (/etc/nixos). See README.\033[0m\n' "$cmd" >&2
    exit 0
  '';

  stubFiles = lib.listToAttrs (map (cmd: {
    name = "${overrideDir}/${cmd}";
    value = { text = stubScript; executable = true; };
  }) disabledCommands);
in
{
  home.file = stubFiles;

  # Covers non-interactive contexts (systemd user units, SSH non-login). The
  # interactive/GUI-terminal win is handled in shell.nix (ordering-guaranteed).
  home.sessionPath = [ overrideDirAbs ];
}
