# Neutralizes Arch-specific Omarchy commands on NixOS.
#
# A handful of `omarchy-*` scripts call pacman/yay or write to /etc, /usr,
# /boot — on NixOS they error or do damage. They live read-only at
# ~/.local/share/omarchy/bin/, so we can't delete them; instead we ship stub
# scripts in an override dir and make that dir win on PATH.
#
# PATH precedence (the tricky part): Omarchy unconditionally re-prepends
# $OMARCHY_PATH/bin in default/bash/envs (sourced by every interactive shell).
# So the override dir must be prepended AFTER that. We do the actual prepend at
# the tail of shell.nix's initExtra (right after sourcing Omarchy's rc), which
# guarantees sequential ordering. This module just creates the stub scripts
# (+ a sessionPath entry for non-interactive/systemd contexts).
{ config, lib, ... }:

let
  overrideDir    = ".local/share/omarchy-nixos-overrides";
  overrideDirAbs = "${config.home.homeDirectory}/${overrideDir}";

  # Arch-specific commands that must not run on NixOS (pacman/yay, mutable
  # /etc, /usr, /boot, and Omarchy-git workflows). The high-level install/remove
  # scripts are included too; otherwise they can continue after a fake
  # omarchy-pkg-add success and leave partial config behind.
  disabledCommands = [
    "omarchy-branch-set"
    "omarchy-channel-set"
    "omarchy-config-direct-boot"
    "omarchy-hibernation-remove"
    "omarchy-hibernation-setup"
    "omarchy-install-browser"
    "omarchy-install-chromium-google-account"
    "omarchy-install-dev-env"
    "omarchy-install-dropbox"
    "omarchy-install-gaming-geforce-now"
    "omarchy-install-gaming-gpu-lib32"
    "omarchy-install-gaming-heroic"
    "omarchy-install-gaming-lutris"
    "omarchy-install-gaming-moonlight"
    "omarchy-install-gaming-retroarch"
    "omarchy-install-gaming-steam"
    "omarchy-install-gaming-xbox-cloud"
    "omarchy-install-gaming-xbox-controllers"
    "omarchy-install-helix"
    "omarchy-install-nordvpn"
    "omarchy-install-once"
    "omarchy-install-tailscale"
    "omarchy-install-vscode"
    "omarchy-install-zed"
    "omarchy-migrate"
    "omarchy-pkg-add"
    "omarchy-pkg-aur-accessible"
    "omarchy-pkg-aur-add"
    "omarchy-pkg-aur-install"
    "omarchy-pkg-drop"
    "omarchy-pkg-install"
    "omarchy-pkg-missing"
    "omarchy-pkg-present"
    "omarchy-pkg-remove"
    "omarchy-plymouth-reset"
    "omarchy-plymouth-set"
    "omarchy-plymouth-set-by-theme"
    "omarchy-refresh-limine"
    "omarchy-refresh-pacman"
    "omarchy-refresh-plymouth"
    "omarchy-refresh-sddm"
    "omarchy-reinstall"
    "omarchy-reinstall-configs"
    "omarchy-reinstall-git"
    "omarchy-reinstall-pkgs"
    "omarchy-remove-browser"
    "omarchy-remove-dev-env"
    "omarchy-remove-gaming-geforce-now"
    "omarchy-remove-gaming-heroic"
    "omarchy-remove-gaming-lutris"
    "omarchy-remove-gaming-minecraft"
    "omarchy-remove-gaming-moonlight"
    "omarchy-remove-gaming-retroarch"
    "omarchy-remove-gaming-steam"
    "omarchy-remove-gaming-xbox-cloud"
    "omarchy-remove-gaming-xbox-controllers"
    "omarchy-remove-preinstalls"
    "omarchy-remove-security-fido2"
    "omarchy-remove-security-fingerprint"
    "omarchy-setup-dns"
    "omarchy-setup-security-fido2"
    "omarchy-setup-security-fingerprint"
    "omarchy-toggle-hybrid-gpu"
    "omarchy-update"
    "omarchy-update-analyze-logs"
    "omarchy-update-aur-pkgs"
    "omarchy-update-branch"
    "omarchy-update-confirm"
    "omarchy-update-git"
    "omarchy-update-keyring"
    "omarchy-update-orphan-pkgs"
    "omarchy-update-perform"
    "omarchy-update-system-pkgs"
  ];

  # One shared body, keyed off $0's basename. It exits non-zero on purpose:
  # package/boot/system installers must not silently pretend they succeeded.
  unsupportedScript = ''
    #!/usr/bin/env bash
    # Auto-generated by modules/omarchy-nixos-compat.nix — do not edit.
    cmd="$(basename "$0")"
    printf '\033[0;33m▲ %s is managed declaratively on NixOS.\033[0m\n' "$cmd" >&2
    printf '  Edit /etc/nixos, then run: sudo nixos-rebuild switch --flake /etc/nixos#toonix\n' >&2
    exit 1
  '';

  stubFiles = lib.listToAttrs (map (cmd: {
    name = "${overrideDir}/${cmd}";
    value = { text = unsupportedScript; executable = true; };
  }) disabledCommands);

  specialFiles = {
    "${overrideDir}/omarchy-update-available" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        # Hide Waybar's Arch/Omarchy-git update indicator on NixOS.
        echo "Toonix updates are managed by NixOS rebuilds." >&2
        exit 1
      '';
    };

    "${overrideDir}/omarchy-update-available-reset" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        pkill -RTMIN+7 waybar 2>/dev/null || true
        exit 0
      '';
    };

    "${overrideDir}/omarchy-update-firmware" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        if ! command -v fwupdmgr >/dev/null 2>&1; then
          echo "fwupdmgr is unavailable; enable services.fwupd in /etc/nixos." >&2
          exit 1
        fi
        fwupdmgr refresh --force
        exec sudo fwupdmgr update
      '';
    };

    "${overrideDir}/omarchy-install-terminal" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail
        if [ "$#" -eq 0 ]; then
          echo "Usage: omarchy-install-terminal [alacritty|foot|ghostty|kitty]" >&2
          exit 1
        fi

        case "$1" in
          alacritty|foot|ghostty|kitty) ;;
          *)
            echo "Unknown terminal: $1" >&2
            exit 1
            ;;
        esac

        if ! command -v "$1" >/dev/null 2>&1; then
          echo "$1 is not installed; add it to environment.systemPackages in /etc/nixos." >&2
          exit 1
        fi

        exec omarchy-default-terminal "$1"
      '';
    };

    "${overrideDir}/omarchy-voxtype-install" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        if ! command -v voxtype >/dev/null 2>&1; then
          echo "voxtype is not installed; add pkgs.voxtype to /etc/nixos." >&2
          exit 1
        fi

        if gum confirm "Download Voxtype AI model (~150MB) and enable dictation?"; then
          mkdir -p "$HOME/.config/voxtype"
          cp "$OMARCHY_PATH/default/voxtype/config.toml" "$HOME/.config/voxtype/config.toml"

          voxtype setup --download --no-post-install
          if omarchy-hw-vulkan; then
            voxtype setup gpu --enable || true
          fi
          voxtype setup systemd
          systemctl --user enable --now voxtype.service 2>/dev/null || true

          omarchy-restart-waybar
          notify-send "    Voxtype Dictation Ready" "Hold F9 to dictate (or toggle with Super + Ctrl + X)." -t 10000
        fi
      '';
    };

    "${overrideDir}/omarchy-voxtype-remove" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        systemctl --user disable --now voxtype.service 2>/dev/null || true
        rm -f "$HOME/.config/systemd/user/voxtype"*
        systemctl --user daemon-reload 2>/dev/null || true
        rm -rf "$HOME/.config/voxtype" "$HOME/.local/share/voxtype"
        omarchy-restart-waybar
        echo "Voxtype user configuration and model data removed. The package remains declared in /etc/nixos."
      '';
    };

    "${overrideDir}/omarchy-voxtype-status" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        if ! command -v voxtype >/dev/null 2>&1; then
          echo '{"alt": "", "tooltip": ""}'
          exit 0
        fi

        if ! systemctl --user is-active --quiet voxtype.service 2>/dev/null; then
          echo '{"alt": "", "tooltip": "Voxtype not configured"}'
          exit 0
        fi

        voxtype status --follow --extended --format json | while read -r line; do
          echo "$line" | jq -c '. + {alt: .class}'
        done
      '';
    };
  };
in
{
  home.file = stubFiles // specialFiles;

  # Covers non-interactive contexts (systemd user units, SSH non-login). The
  # interactive/GUI-terminal win is handled in shell.nix (ordering-guaranteed).
  home.sessionPath = [ overrideDirAbs ];
}
